Multy/AppDelegate.swift
Multy/Cells/MainWallet/EthWallet/EthWalletHeaderCollectionViewCell.swift
Multy/DataManagers/DataManager.swift
Multy/Extensions/Constants.swift
Multy/Model/Realm/Wallets/ETHWallet.swift
Multy/Protocols/ContactProtocol.swift
Multy/Storyboards/Base.lproj/Main.storyboard
Multy/ViewControllers and Presenters/Assets/TermsOfService/TermsOfServiceViewController.swift
Multy/ViewControllers and Presenters/TabBar/Settings/SettingsViewController.swift
Multy/ViewControllers and Presenters/Wallet/BTCWallet/BTCWalletViewController.swift
Podfile

Updated push functionailty, wallet info for ETH

Updated functionailty

---

Multy/Extensions/AnalyticsConstants.swift
Multy/ViewControllers and Presenters/Receive/ReceiveAllDetails/ReceiveAllDetailsPresenter.swift
Multy/ViewControllers and Presenters/Receive/ReceiveAllDetails/ReceiveAllDetailsViewController.swift
Multy/ViewControllers and Presenters/Send/Send/SendPresenter.swift
Multy/ViewControllers and Presenters/Send/Send/SendViewController.swift

updated Killer Feature analytics

updated analytics

---

Multy/Protocols/ContactProtocol.swift

added Multy-link to contact if there added address

added Multy-link to contact

---

Multy/Storyboards/Base.lproj/Wallet.storyboard
Multy/ViewControllers and Presenters/Wallet/Wallet/WalletViewController.swift

when tapped on navigation bar title

hiding transactions history table 

---

Multy/DataManagers/RealmManager.swift
Multy/Extensions/Constants.swift

added creating ETH MAIN NET

---

Multy/ViewControllers and Presenters/Send/SendStart/SendStartViewController.swift

Fixed nextAction on send screen

Fixed nextAction on send screen

---

Multy/Cells/MainWallet/EthWallet/EthWalletHeaderCollectionViewCell.swift
Multy/Model/Realm/UserWalletRLM.swift
Multy/Model/Realm/Wallets/ETHWallet.swift

updated wallet's amount logic

---

Multy/DataManagers/CoreLibManager.swift
Multy/DataManagers/DataManagerExtensions/DMApiExtension.swift
Multy/Extensions/Constants.swift
Multy/ViewControllers and Presenters/Assets/Creating wallet/CreateMultiSig/CreateMultiSigPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Wallet/WalletPresenter.swift

added confirmation core lib method, fixed creating MS wallet

added confirmation core lib method, fixed creating MS wallet

---

Multy/DataManagers/RealmManager.swift
Multy/Extensions/Constants.swift
Multy/ViewControllers and Presenters/Assets/AssetsPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Wallet settings/WalletSettingsPresenter.swift

fixed deleting wallet from realm

fixed deleting wallet from realm

---

Multy/Model/PONSO/EthereumGasInfo.swift
Multy/ViewControllers and Presenters/Send/Send/SendPresenter.swift
Multy/ViewControllers and Presenters/Send/SendAmount/ETH/SendAmountEthPresenter.swift

increased gas limit up to 40000

increased gas limit

---

Multy/DataManagers/DataManager.swift
Multy/DataManagers/DataManagerExtensions/DMApiExtension.swift
Multy/DataManagers/DataManagerExtensions/DMCoreLibExtension.swift
Multy/DataManagers/RealmManager.swift
Multy/Security/MasterKeyGenerator.swift
Multy/ViewControllers and Presenters/Assets/AssetsViewController.swift

added parsing multisig factories

added parsing multisig factories

---

Multy/Additional Libraries/Core Libs/blockchain.h

added EOS into blockchain list

added EOS into blockchain list

---

Multy/Storyboards/Base.lproj/Send.storyboard
Multy/ViewControllers and Presenters/Send/SendStart/SendStartPresenter.swift
Multy/ViewControllers and Presenters/Send/SendStart/SendStartViewController.swift
Multy/ViewControllers and Presenters/Send/WalletChoose/WalletChoosePresenter.swift
Multy/ViewControllers and Presenters/Send/WalletChoose/WalletChooseViewController.swift

added in EOS skip selection fee rates

added in EOS skip selection fee rates

---

Multy/DataManagers/RealmManager.swift
Multy/Model/Realm/UserWalletRLM.swift

 fixed EOS balance 

---

Multy.xcodeproj/project.pbxproj
Multy/Protocols/EOSNewWalletProtocol.swift
Multy/ViewControllers and Presenters/Assets/AssetsPresenter.swift
Multy/ViewControllers and Presenters/Assets/AssetsViewController.swift
Multy/ViewControllers and Presenters/Import/EOSAccountViewController/EOSAccountsPresenter.swift
Multy/ViewControllers and Presenters/Import/EOSAccountViewController/EOSAccountsViewController.swift
Multy/ViewControllers and Presenters/Import/ImportWalletPresenter.swift
Multy/ViewControllers and Presenters/Import/ImportWalletViewController.swift
Multy/ViewControllers and Presenters/Send/SendAmount/ETH/SendAmountEthPresenter.swift

updated send tx functionality

---

Multy/ViewControllers and Presenters/Send/SendAmount/ETH/SendAmountEthPresenter.swift
Multy/ViewControllers and Presenters/Send/SendAmount/ETH/SendAmountEthViewController.swift
Multy/ViewControllers and Presenters/Wallet/Wallet/WalletPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Wallet/WalletViewController.swift

update send tx

---

Multy/DataManagers/CoreLibManager.swift
Multy/DataManagers/DataManagerExtensions/DMCoreLibExtension.swift
Multy/DataManagers/RealmManager.swift
Multy/DataManagers/Socket.swift
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersPresenter.swift
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersViewController.swift

add pay for creating MS wallet

add pay for creating MS wallet

---

Multy/DataManagers/CoreLibManager.swift
Multy/DataManagers/DataManagerExtensions/DMRealmExtension.swift
Multy/DataManagers/RealmManager.swift
Multy/Model/Realm/UserWalletRLM.swift
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersPresenter.swift

deploy multisig wallet

---

Multy/Extensions/LocalizationConstant.swift
Multy/Localized Strings/en.lproj/CreateMultiSig.strings
Multy/Localized Strings/ru.lproj/CreateMultiSig.strings
Multy/Localized Strings/uk.lproj/CreateMultiSig.strings
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersPresenter.swift
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersViewController.swift

updated statuses functionality and transition to MS wallet

Creating multi sig wallet statuses functionality

---

Multy/ViewControllers and Presenters/Wallet/Transaction/TransactionPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Transaction/TransactionViewController.swift
Multy/ViewControllers and Presenters/Wallet/Wallet/WalletPresenter.swift

added tx history and stub for 'confirm' method for multisig wallet

added tx history and 'confirm' method

---

Multy/Extensions/LocalizationConstant.swift
Multy/Extensions/MultisigConstants.swift
Multy/Localized Strings/en.lproj/CreateMultiSig.strings
Multy/Localized Strings/ru.lproj/CreateMultiSig.strings
Multy/Localized Strings/uk.lproj/CreateMultiSig.strings
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersPresenter.swift
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersViewController.swift
Multy/ViewControllers and Presenters/Send/SendAmount/ETH/SendAmountEthPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Wallet/WalletPresenter.swift

fix creating MS wallet and estimations

creating MS wallet and fix estimations

---

Multy/DataManagers/Socket.swift
Multy/Extensions/Constants.swift
Multy/Extensions/UIViewController+Extension.swift
Multy/Localized Strings/en.lproj/CreateMultiSig.strings
Multy/Localized Strings/ru.lproj/CreateMultiSig.strings
Multy/Localized Strings/uk.lproj/CreateMultiSig.strings
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersPresenter.swift
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersViewController.swift

updated socket events for multisig

updated socket events for multisig

---

Multy/DataManagers/Socket.swift
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersPresenter.swift

updated multisig events handling

updated multisig events handling

---

Multy/Extensions/BlockchainType+Extension.swift
Multy/Model/Realm/Wallets/MultisigWallet.swift
Multy/ViewControllers and Presenters/Receive/ReceiveAllDetails/ReceiveAllDetailsPresenter.swift
Multy/ViewControllers and Presenters/Receive/ReceiveAllDetails/ReceiveAllDetailsViewController.swift
Multy/ViewControllers and Presenters/Receive/StartReceive/ReceiveStartPresenter.swift
Multy/ViewControllers and Presenters/Send/WalletChoose/WalletChoosePresenter.swift

updated multisig functionality for KF and filtering not deployed wallets

updated multisig functionality for KF and filtering not deployed wallets

---

Multy/DataManagers/DataManagerExtensions/DMSocketExtension.swift
Multy/Storyboards/Base.lproj/Wallet.storyboard
Multy/ViewControllers and Presenters/Assets/AssetsViewController.swift
Multy/ViewControllers and Presenters/Send/Send/SendPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Transaction/TransactionPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Transaction/TransactionViewController.swift

added showing no balance view, notification on assets screen

Creating ms wallet

---

Multy/ViewControllers and Presenters/Wallet/Wallet/WalletPresenter.swift

fixed checking eth wallet balance

fixed checking eth wallet balance

---

Multy/ViewControllers and Presenters/Wallet/Transaction/TransactionPresenter.swift

added checking MS available amount while confirming tx from MS wallet

added checking MS available amount while confirming tx from MS wallet

---

Multy/ViewControllers and Presenters/Wallet/Transaction/TransactionPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Transaction/TransactionViewController.swift

updated bottom slider

---

Multy/DataManagers/DataManagerExtensions/DMCoreLibExtension.swift

fixed send tx for imported MS wallet

fixed send tx for imported MS wallet

---

Multy/ViewControllers and Presenters/Assets/Creating wallet/ImportMS/ImportMSPresenter.swift

updated MS import functionality

updated MS import functionality

---

Multy/DataManagers/CoreLibManager.swift
Multy/Extensions/String+Extension.swift

updated creating ETH TX with payload

updated creating ETH TX with payload

---

Multy/DataManagers/CoreLibManager.swift
Multy/Extensions/String+Extension.swift

added payload to tx with default empty value

added payload section to tx

---

Multy/Info.plist

updated 'master' branch name

---

Multy/ViewControllers and Presenters/Send/SendStart/SendStartPresenter.swift

fixed nil choosen wallet while scanning address qr-code

fixed nil choosen wallet

---

Multy.xcodeproj/project.pbxproj
Multy/DappBrowser/BrowserCoordinator.swift
Multy/DappBrowser/BrowserViewController.swift
Multy/Info.plist
Multy/Localized Strings/en.lproj/DappBrowser.strings
Multy/Localized Strings/ru.lproj/DappBrowser.strings
Multy/Localized Strings/uk.lproj/DappBrowser.strings
Multy/ViewControllers and Presenters/TabBar/Browser/DappBrowserPresenter.swift
Multy/ViewControllers and Presenters/TabBar/Browser/DappBrowserViewController.swift

refactored browser initialization, added localization, fixed changing address for WebView

Dapp browser

---

Multy/AppDelegate.swift
Multy/DappBrowser/BrowserCoordinator.swift
Multy/DappBrowser/BrowserViewController.swift
Multy/Extensions/Constants.swift
Multy/ViewControllers and Presenters/TabBar/Browser/DappBrowserPresenter.swift
Multy/ViewControllers and Presenters/TabBar/Browser/DappBrowserViewController.swift

updated url functionality

---

Multy.xcodeproj/project.pbxproj
Multy/DappBrowser/BrowserViewController.swift
Multy/Extensions/AnalyticsConstants.swift

changed url field, added Smart Contract field

Dapp browser: improved analytic events

---

Multy.xcodeproj/project.pbxproj
Multy/AppDelegate.swift
Multy/DataManagers/ApiManager.swift
Multy/Info.plist
Podfile

fixed fcm token

---

Multy/ViewControllers and Presenters/Assets/AssetsViewController.swift
Multy/ViewControllers and Presenters/Receive/ReceiveAllDetails/ReceiveAllDetailsPresenter.swift
Multy/ViewControllers and Presenters/Receive/ReceiveAllDetails/ReceiveAllDetailsViewController.swift

fixed missing wallet address and creating first wallets twice

 fixed missing wallet address and creating first wallets twice 

---

Multy/Additional Resources/BricksView.swift
Multy/DataManagers/CoreLibManager.swift
Multy/DataManagers/DataManager.swift
Multy/DataManagers/DataManagerExtensions/DMCoreLibExtension.swift
Multy/DataManagers/RealmManager.swift
Multy/Extensions/AccountType.swift
Multy/ViewControllers and Presenters/Assets/AssetsViewController.swift
Multy/ViewControllers and Presenters/CreateMultiSig/WaitingMembers/WaitingMembersPresenter.swift
Multy/ViewControllers and Presenters/Seed Phrase/Check Phrase/CheckWordsViewController.swift
Multy/ViewControllers and Presenters/Seed Phrase/Phrase Word/SeedPhraseWordPresenter.swift
Multy/ViewControllers and Presenters/Send/Send/SendPresenter.swift
Multy/ViewControllers and Presenters/Send/SendAmount/SendAmountPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Transaction/TransactionPresenter.swift

implemented JSON-API for all ETH requests, fixed sending ETH testnet, fixed metamask seed phrase

implemented JSON-API

---

Multy/Additional Resources/BricksView.swift
Multy/DataManagers/CoreLibManager.swift
Multy/DataManagers/DataManager.swift
Multy/DataManagers/DataManagerExtensions/DMCoreLibExtension.swift
Multy/DataManagers/DataManagerExtensions/DMRealmExtension.swift
Multy/DataManagers/RealmManager.swift
Multy/Extensions/AccountType.swift
Multy/Model/Realm/HistoryRLM.swift
Multy/ViewControllers and Presenters/Assets/AssetsPresenter.swift
Multy/ViewControllers and Presenters/Assets/AssetsViewController.swift
Multy/ViewControllers and Presenters/Receive/StartReceive/ReceiveStartPresenter.swift
Multy/ViewControllers and Presenters/Seed Phrase/Backup Phrase/BackupSeedPhraseViewController.swift
Multy/ViewControllers and Presenters/Seed Phrase/Check Phrase/CheckWordsViewController.swift
Multy/ViewControllers and Presenters/Seed Phrase/Congratulations/BackupFinishViewController.swift
Multy/ViewControllers and Presenters/Seed Phrase/MetaMaskInfo/ImportMetaMaskInfoViewController.swift
Multy/ViewControllers and Presenters/Send/Send/SendPresenter.swift
Multy/ViewControllers and Presenters/Send/SendAmount/SendAmountPresenter.swift
Multy/ViewControllers and Presenters/TabBar/Browser/DappBrowserPresenter.swift
Multy/ViewControllers and Presenters/Wallet/Wallet/WalletPresenter.swift

fixed import metamask, updated coreLib path call, fixed info from coreLib

Metamask functionality

---

Multy/Cells/Portfolio/DonationCollectionViewCell.swift
Multy/Extensions/LocalizationConstant.swift
Multy/Localized Strings/en.lproj/Seed.strings
Multy/Localized Strings/en.lproj/Sends.strings
Multy/Localized Strings/ru.lproj/Seed.strings
Multy/Localized Strings/ru.lproj/Sends.strings
Multy/Localized Strings/uk.lproj/Seed.strings
Multy/Localized Strings/uk.lproj/Sends.strings
Multy/ViewControllers and Presenters/Send/CustomFee/CustomFeeViewController.swift
Multy/ViewControllers and Presenters/Send/SendAmount/SendAmountViewController.swift

small fixes

---

Multy/Model/PONSO/TransactionDTO/TransactionDTO.swift
Multy/Model/Realm/HistoryRLM.swift
Multy/ViewControllers and Presenters/Send/SendAmount/SendAmountPresenter.swift
Multy/ViewControllers and Presenters/Send/WalletChoose/WalletChoosePresenter.swift

fixes: data from qr, blocktime in txHistory, fixed segue

fixes: data from qr, blocktime in txHistory, fixed segue

---

Multy/Extensions/Constants.swift

updated url

---

Multy/Cells/RecentAddresses/RecentAddressTableViewCell.swift
Multy/Info.plist
Multy/Model/Realm/RecentAddressesRLM.swift
Multy/Storyboards/Base.lproj/Send.storyboard
Multy/ViewControllers and Presenters/Send/Finish/SendFinishViewController.swift
Multy/ViewControllers and Presenters/Send/SendAmount/SendAmountPresenter.swift
Multy/ViewControllers and Presenters/Send/SendDetails/SendDetailsViewController.swift
Multy/ViewControllers and Presenters/Send/SendStart/SendStartPresenter.swift
Multy/ViewControllers and Presenters/Send/SendStart/SendStartViewController.swift
Multy/ViewControllers and Presenters/Wallet/Wallet/WalletPresenter.swift

fixed available balance in 'token' TableView, updated donation section for SendDetailVC

Update release 1.5

---

Multy/ViewControllers and Presenters/Wallet/Transaction/ViewInBlockchain/ViewInBlockchainViewController.swift

fixed explorer url for btc

---

Multy/Extensions/Constants.swift
Multy/Model/Realm/HistoryRLM.swift
Multy/ViewControllers and Presenters/Wallet/Transaction/ViewInBlockchain/ViewInBlockchainViewController.swift

fixed txID and added stage server to comments

fixed old txID value
